version: '3.8'

services:
  db:
    image: postgres:16
    env_file:
      - ./docker_env/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./docker_env/.env
    ports:
      - "15432:80"
  redis:
    image: redis/redis-stack:7.2.0-v11
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"
      - "8001:8001"