version: '3.8'

services:
  api:
    image: dauid64/tutoria1.0
    env_file:
      - ./docker_env/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:16
    env_file:
      - ./docker_env/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./docker_env/.env
    ports:
      - "15432:80"
    