version: '3.8'

services:
  api:
    image: dauid64/tutoria1.0
    env_file:
      - ./docker_env/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - ./docker_env/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    