[env]

RUST_LOG="tutorIA_API=debug"

SERVICE_PORT="3000"

DATABASE_URL="postgres://user:pwd@localhost/db"


SECRET_JWT="CHANGE-ME"

# For Base64-URL
PWD_KEY="CHANGE-ME"

SQLX_OFFLINE="true"

WEB_FOLDER="static/"

OPENAI_API_KEY="CHANGE-ME"

TUTORIA_MODEL="gpt-3.5-turbo"